In [0]:
name=input("enter name:")
if name=="jyothsna":
  print("hello jyothsna good afternoon")
print("heelo how are you")  

enter name:jyothsna
hello jyothsna good afternoon
dont know the name


In [0]:
name=input("enter name:")
if name=="jyothsna":
  print("hello jyothsna good afternoon")
else:
  print("i dont know ur name")
print("hello how are you")  
    

enter name:jyothsna
hello jyothsna good afternoon
hello how are you


In [0]:
team=input("enter your favourite team")
if team=="MNU":
  print("its maneschester united")
elif team=="CHL":
  print("its chesla")
else:
  print("playing for an unknown team")


enter your favourite teamMNU
its maneschester united


In [0]:
s="Sachiin tendulkar"
for x in s:
  print(x)
  

S
a
c
h
i
i
n
 
t
e
n
d
u
l
k
a
r


In [0]:
for x in range(11):
  print(x)
  

0
1
2
3
4
5
6
7
8
9
10


In [0]:
for x in range(0,21):
 if(x%2==0):
  print(x)
  

0
2
4
6
8
10
12
14
16
18
20


In [0]:
for x in range (1,10,2):
 print(x)


1
3
5
7
9


In [0]:
for i in range(4):
  for j in range(4):
    print("i=",i,"j=",j)

i= 0 j= 0
i= 0 j= 1
i= 0 j= 2
i= 0 j= 3
i= 1 j= 0
i= 1 j= 1
i= 1 j= 2
i= 1 j= 3
i= 2 j= 0
i= 2 j= 1
i= 2 j= 2
i= 2 j= 3
i= 3 j= 0
i= 3 j= 1
i= 3 j= 2
i= 3 j= 3


In [0]:
for i in range(1,5):
  for j in range(1,i+1):
    print("*",end="")
  print()  

*
**
***
****


In [0]:
for i in range(10):
  if i==7:
    print("lets break after 7")
    break
    print(i)
    
    
    

lets break after 7


In [0]:
cart=[100,200,300,500,600,700]
for x in cart:
   if x>=500:
      print("it should be insured")
      break


it should be insured


In [0]:
dict1={"H":"Hydrogen","N":"Nitrogen"}
dict1["N"]


'Nitrogen'

In [0]:
dict1={"INDIA":"VIRAT KOHLI","PAKISTHAN":"MOHAMMAMAD","AUSTRALIA":"STEEVES"}
dict1["INDIA"]

'VIRAT KOHLI'

In [2]:
for i in range(1,6):
  for j in range(1,i+1):
    print("v",end="")
    print("i",end="")
    
    print()
  print()  

vi

vi
vi

vi
vi
vi

vi
vi
vi
vi

vi
vi
vi
vi
vi



In [1]:
list=['rahul','jyothsna']
for i in list:
    print("happy new year ",i)
    

happy new year  rahul
happy new year  jyothsna


In [16]:
for i in range(0,4):
    for j in range(0,4):
        if i+j<=2:
            print(" ",end=" ")
        if i+j>=3:
            print("*",end=" ")
    print( )

      * 
    * * 
  * * * 
* * * * 


In [15]:
for i in range(0,4):
    for j in range(0,4):
        
        if i+j>=3:
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print( )
    

      * 
    * * 
  * * * 
* * * * 


In [22]:
name=input("enter the name")
x=len(inp)/2
for i in range(len(name)):
    for j in range(0,i+1):
        print(name[i],end=' ')
    print( )
    
    
    

enter the namevirat
v 
i i 
r r r 
a a a a 
t t t t t 


In [23]:
rec={}
n=int(input("enter the number of students:"))
i=1
while i<=n:
    name=input("enter student name:")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
    
print("name of student","\t","% of marks",name,marks)
for x in rec:
    print("\t",x,"\t\t",rec[x])

enter the number of students:4
enter student name:rahul
enter % marks of student90
enter student name:jyothsna
enter % marks of student90
enter student name:madhura
enter % marks of student80
enter student name:prajna
enter % marks of student80
name of student 	 % of marks prajna 80
	 rahul 		 90
	 jyothsna 		 90
	 madhura 		 80
	 prajna 		 80


In [24]:
d={100:'hello',2:'MITE',3:'Rahul'}
print(d)

{100: 'hello', 2: 'MITE', 3: 'Rahul'}


In [25]:
d[100]="sunny"

In [26]:
print(d)

{100: 'sunny', 2: 'MITE', 3: 'Rahul'}


In [27]:
del d[2]
print(d)

{100: 'sunny', 3: 'Rahul'}


In [28]:
d[2]="Jyothsna"
print(d)

{100: 'sunny', 3: 'Rahul', 2: 'Jyothsna'}


In [29]:
d.clear()
print(d)

{}


In [30]:
d={100:'hello',2:'MITE',3:'Rahul',4:400}
print(d)

{100: 'hello', 2: 'MITE', 3: 'Rahul', 4: 400}


In [34]:
d={100:'hello',2:'MITE',3:'Rahul',4:400}
len(d)


4

In [36]:
word=input("ENTER ANY WORD")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occured",v,"times")

ENTER ANY WORDhheeeelooo
h occured 2 times
e occured 4 times
l occured 1 times
o occured 3 times


In [41]:
word=input("ENTER ANY WORD ")
d={}
for x in word:
    if(x=='a' or x=='e' or x=='i' or x=='o' or x=='u' or x=='A' or x=='E' or x=='I' or x=='O' or x=='U'):
        d[x]=d.get(x,0)+1
    else:
        d[x]=d.get(x,0)
for k,v in d.items():
    print(k,"occured",v,"times")

ENTER ANY WORD rahul
r occured 0 times
a occured 1 times
h occured 0 times
u occured 1 times
l occured 0 times


In [40]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
word=input("ENTER ANY WORD ")
d={}
vowels={'a','e','i','o','u'}
for x in word:
    if(vowels):
        d[x]=d.get(x,0)+1
    else:
        d[x]=d.get(x,0)
for k,v in d.items():
    print(k,"occured",v,"times")

In [44]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))


4


In [46]:
print(n.index(5))

4


In [47]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


In [52]:
list1=[1,2,3,'hello']
list2=[4,5,6,'india']
list1.extend(list2)
print(list1)


[1, 2, 3, 'hello', 4, 5, 6, 'india']


####
list1.remove(3)

In [53]:
list1.remove(3)
print(list1)

[1, 2, 'hello', 4, 5, 6, 'india']


In [54]:
n.pop()

5

In [55]:
print(list1)

[1, 2, 'hello', 4, 5, 6, 'india']


###reverse the string

In [56]:
list1.reverse()
print(list1)

['india', 6, 5, 4, 'hello', 2, 1]


In [81]:
list3=['jos','madhu','prajna']
list1.extend(list3)
n.sort()
print(list1)


['india', 6, 5, 4, 'hello', 2, 1, 'jos', 'madhu', 'prajna', 'jos', 'madhu', 'prajna', 'jos', 'madhu', 'prajna', 'jos', 'madhu', 'prajna', 'jos', 'madhu', 'prajna', 'jos', 'madhu', 'prajna', 'jos', 'madhu', 'prajna']


In [61]:
n.sort()

In [77]:
d=[1,'rahul',4,'jos',3,'madhu']
print(n.sort())


None


copy by value and referrence

In [83]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [84]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [85]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [86]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [87]:
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [89]:
x=["MITE","Mangalore","NITTE"]
y=["MITE","Mangalore","NITTE"]
z=["MITE","Mangalore","NITTE"]
if(x==y):
    print("yes")
if(x!=y):
    print("yeah")
if(x==z):
    print("yessss")

yes
yessss


In [90]:
m=[10,20,30,40,[50,60,70]]
print(m[3])
print(m[4][1])

40
60


In [97]:
n=[1,2,3,4]
print(4 in 1)

TypeError: argument of type 'int' is not iterable

In [98]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [99]:
words=["Mite","Mysore","Anubhav"]
l=[w[0] for w in words]
print(l)

['M', 'M', 'A']


In [102]:
def prime(n):
    if(n%2==0):
        prime=1
inp=input("enter the number")
prime(x)
if prime==0:
    print("its a prime number")
else:
    print("its not prime number")

enter the numbery7


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [115]:
list=[2,4,6,8,10]
def time2(var):
    return var*2
seq=[1,2,3,4,5]
list(map(time2,seq))

TypeError: 'list' object is not callable

In [114]:
seq=[1,2,3,4,5]

lambda var: var*2
list(map(lambda var: var*2,seq))
list(filter(lambda item:item%2==0,seq))

TypeError: 'list' object is not callable

In [117]:
import numpy as np
my_list=[1,2,3]
print(my_list)
np.array(my_list)

[1, 2, 3]


array([1, 2, 3])

In [121]:
my_matrix=[1,2,3],[4,5,6],[7,8,9]
print(my_matrix)
np.array(my_matrix)



([1, 2, 3], [4, 5, 6], [7, 8, 9])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.zeros(3)

array([0., 0., 0.])

In [124]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [125]:
np.ones(3)

array([1., 1., 1.])

In [126]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [127]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [128]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [129]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [131]:
np.random.rand(2)

array([0.43960923, 0.23035481])

In [132]:
np.random.rand(5,5)

array([[0.82825208, 0.80179768, 0.26856936, 0.80889548, 0.85222818],
       [0.11649748, 0.00537383, 0.60790944, 0.85181301, 0.23617969],
       [0.37672567, 0.1232095 , 0.73803715, 0.09930742, 0.78232665],
       [0.83374157, 0.50111885, 0.73947115, 0.68376971, 0.38995329],
       [0.0440582 , 0.67900359, 0.61527633, 0.43512094, 0.36765845]])

In [133]:
np.random.randn(5,5)

array([[ 1.48218222, -0.61097006, -0.37770085,  1.45980829,  0.32426954],
       [-2.64429263,  0.82926834,  0.32211517,  0.35675215,  0.51699106],
       [-0.16879356, -0.8218351 , -3.0124155 , -0.44752733,  1.14513629],
       [-0.12117027,  0.37371271, -0.75667427, -0.44737364,  0.69255053],
       [-0.7754214 ,  0.20210547,  1.36059394, -1.33672125,  1.51859618]])

In [134]:
np.random.randint(1,100,10)

array([27, 98, 97, 89, 47, 93, 42, 39, 61, 83])

In [135]:
ar=np.random.randint(1,100,10)
print(ar)

[49 46 57 21 56 70 91  1 57 17]


In [136]:
arr=np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [138]:
runarr=np.random.randint(0,50,10)
print(runarr)

[47 26 23 42 29 18  4 45  2 17]


In [197]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 11 into shape (5,5)

In [145]:
runarr.max()


47

In [147]:
runarr.argmin()

8

In [146]:
runarr.min()

2

In [148]:
runarr.argmax()


0

In [149]:
arr.shape

(25,)

In [150]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [151]:
arr.reshape(1,25).shape

(1, 25)

In [152]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [153]:
arr.reshape(25,1).shape

(25, 1)

In [155]:
arr.dtype

dtype('int32')

In [160]:
arr=np.arange(0,10)

arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [161]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [162]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [164]:
arr/arr

C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [165]:
1/arr

C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [166]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [167]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [168]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [169]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [170]:
np.log(arr)

C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [172]:
arr=np.arange(0,11)
print(arr)
arr[8]


[ 0  1  2  3  4  5  6  7  8  9 10]


8

In [173]:
arr[1:5]


array([1, 2, 3, 4])

In [174]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [178]:
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [180]:
arr=np.arange(0,11)
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [181]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [190]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 11 into shape (3,3)

In [191]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [192]:
np.arange(0,25,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [193]:
np.arange(10,80,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

TypeError: reshape() missing 1 required positional argument: 'newshape'

In [201]:
arr_list=[[0,1,2],[3,4,5],[6,7,8]]
np.array(arr_list)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])